services:
  # for development purposes
  dev:
    build: .
    volumes:
        - ./:/code
        - ./data:/data
    environment:
      - KBC_DATADIR=./data
  test:
    # Use to run flake8 and unittests checks
    build: .
    depends_on:
      ftp:
        condition: service_started
      sftp:
        condition: service_started
    volumes:
      - ./:/code
      - ./data:/data
    environment:
      - KBC_DATADIR=./data
    command:
    - /bin/sh
    - -c
    - |
      echo "Waiting for FTP"
      for i in $(seq 1 30); do nc -z ftp 21 && break || sleep 1; done
  
      echo "Waiting for SFTP"
      for i in $(seq 1 30); do nc -z sftp 22 && break || sleep 1; done
  
      /bin/sh /code/scripts/build_n_test.sh

  ftp:
    image: fauria/vsftpd
    ports:
      - "21:21"
      - "21100-21110:21100-21110"
    environment:
      - FTP_USER=user
      - FTP_PASS=pass
    volumes:
      - ./tests/expected_server_data/ftp:/home/vsftpd/user

  sftp:
    image: atmoz/sftp
    ports:
      - "2222:22"
    volumes:
      - ./tests/expected_server_data/sftp/:/home/user/upload
    command: user:pass:${HOST_UID}:${HOST_GID}:upload
